dataset: 'AirfRans'
model: 'LNO'
data_path: 'your_data_path'
vae_pth: ['your_vae_checkpoint_path']
geom_types: ["4_5_digits"]
num_geom: [200]
val_num_geom: [200]
output_dir: "your_output_dir"
log_dir: "your_log_dir"

use_mesh: false
use_VAE: true

trunk_size: 5
branch_sizes: [32]
n_layer: 8
n_hidden: 128
n_head: 4
num_queries: 4096