dataset: 'Elec'
model: 'LNO'
data_path: 'your_data_path'
vae_pth: null
geom_types: ["elec_0_3_0_7_0_2"]
num_geom: [1800]
val_num_geom: [200]
output_dir: "your_output_dir"
log_dir: "your_log_dir"

use_mesh: true
use_VAE: false

trunk_size: 3
branch_sizes: [2]
n_layer: 8
n_hidden: 128
n_head: 4
num_queries: 4096