dataset: 'Stress'
model: 'LNO'
data_path: 'your_data_path'
vae_pth: null
geom_types: ["ellipse_0_3_0_15_0_5_0_5"]
num_geom: [1900]
val_num_geom: [200]
output_dir: "your_output_dir"
log_dir: "your_log_dir"

use_mesh: true
use_VAE: false

trunk_size: 3
branch_sizes: [2]
n_layer: 8
n_hidden: 256
n_head: 8
num_queries: 4096