batch_size: 50
dataset: 'Inductor'
data_path: 'your_data_path'
geom_types: ["EECore_new"]
num_geom: [3600]
val_num_geom: [300]
output_dir: "your_output_dir"
log_dir: "your_log_dir"
dim: 256
num_latents: 256
latent_dim: 32
depth: 6
kl_weight: 0.001